# Site
name: "Murto Hilali"
title: "Murto Hilali"
description: "Hi! I'm Murto. Weekly thoughts on tech, business, and behaviours from an 18 y/o entrepreneur."
logo: 'assets/images/PersonalLogo-2-transparent.png'
favicon: 'assets/images/PersonalLogo-2-transparent.png'
baseurl: /blog
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: hilali.murto@gmail.com

# Authors
authors:
  sal:
    name: sal
    display_name: sal
    avatar: 'assets/images/Headshot-Square.jpg'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: 
    web: 
    twitter: 
    description: ""
  Murto:
    name: Murto
    display_name: Murto    
    avatar: 'assets/images/Headshot-Square.jpg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: hilali.murto@gmail.com
    web: https://www.linkedin.com/in/murtohilali/
    twitter: https://twitter.com/MurtoHilali
    description: "18 y/o student and entrepreneur in Toronto, Canada. Interested in all things innovation, tech, business, economics, psychology, and growth."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: $yellow
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
